# Generated by Django 4.2.20 on 2026-03-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='producto',
        ),
    ]
