# Generated by Django 4.2.20 on 2026-03-29 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedidos_cantidad_remove_pedidos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default=datetime.date(2026, 3, 29)),
        ),
    ]
